#!/bin/bash


echo "performance" > /sys/devices/system/cpu/cpufreq/policy3/scaling_governor


#USO ./travaclock disable|enable   disable para travar na frequencia de fabrica maxima
#SCRIPT PEGO NA INTERNET LINK ORIGINAL: http://notepad2.blogspot.com/2014/11/a-script-to-turn-off-intel-cpu-turbo.html
#creditos do criador original "Wei Liu" : https://github.com/xtman 
if [[ -z $(which rdmsr) ]]; then
    echo "msr-tools is not installed. Run 'sudo apt-get install msr-tools' to install it." >&2
    exit 1
fi

if [[ ! -z $1 && $1 != "enable" && $1 != "disable" ]]; then
    echo "Invalid argument: $1" >&2
    echo ""
    echo "Usage: $(basename $0) [disable|enable]"
    exit 1
fi

cores=$(cat /proc/cpuinfo | grep processor | awk '{print $3}')
for core in $cores; do
    if [[ $1 == "disable" ]]; then
        sudo wrmsr -p${core} 0x1a0 0x4000850089
    fi
    if [[ $1 == "enable" ]]; then
        sudo wrmsr -p${core} 0x1a0 0x850089
    fi
    state=$(sudo rdmsr -p${core} 0x1a0 -f 38:38)
    if [[ $state -eq 1 ]]; then
        echo "core ${core}: disabled"
    else
        echo "core ${core}: enabled"
    fi
done
###############################################################################
sleep 1 
lscpu | grep -i mhz | grep -e "CPU MHz" 